fix aws cli install

diff --git a/.github/workflows/positron-full-test.yml b/.github/workflows/positron-full-test.yml
--- a/.github/workflows/positron-full-test.yml
+++ b/.github/workflows/positron-full-test.yml
@@ -223,6 +223,19 @@ jobs:
         with:
           node-version-file: .nvmrc
 
+      - name: Install AWS CLI
+        shell: bash
+        run: |
+          # Check if AWS CLI is already installed; if not, install it
+          if ! command -v aws &> /dev/null; then
+            echo "AWS CLI not found. Installing..."
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+          else
+            echo "AWS CLI is already installed."
+          fi
+
       - name: Download blob reports
         uses: actions/download-artifact@v4
         with:
