split wflow

diff --git a/.github/workflows/positron-merge-to-main.yml b/.github/workflows/positron-merge-to-main.yml
--- a/.github/workflows/positron-merge-to-main.yml
+++ b/.github/workflows/positron-merge-to-main.yml
@@ -27,8 +27,8 @@ permissions:
   contents: read
 
 jobs:
-  e2e-playwright:
-    timeout-minutes: 30
+  e2e-tests-pw:
+    timeout-minutes: 20
     runs-on: ubuntu-latest-8x
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -73,10 +73,10 @@ jobs:
           name: playwright-report
           path: playwright-report/
           retention-days: 7
-  linux:
-    name: Tests on Linux
+
+  e2e-tests-mocha:
     runs-on: ubuntu-latest-8x
-    timeout-minutes: 45
+    timeout-minutes: 30
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       POSITRON_BUILD_NUMBER: 0 # CI skips building releases
@@ -109,17 +109,6 @@ jobs:
           aws-region: ${{ secrets.QA_AWS_REGION }}
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
-      # - name: Compile Integration Tests
-      #   run: yarn --cwd test/integration/browser compile
-
-      # - name: Run Unit Tests (node.js)
-      #   id: nodejs-unit-tests
-      #   run: yarn test-node
-
-      # - name: Run Integration Tests (Electron)
-      #   id: electron-integration-tests
-      #   run: DISPLAY=:10 ./scripts/test-integration-pr.sh
-
       - name: Run Smoke Tests (Electron)
         if: success() || failure()
         env:
@@ -128,14 +117,14 @@ jobs:
         id: electron-smoke-tests
         run: DISPLAY=:10 yarn ${{ env.SMOKETEST_TARGET }} --tracing --parallel --jobs 2 --skip-cleanup
 
-      # - name: Convert XUnit to JUnit
-      #   id: xunit-to-junit
-      #   if: success() || failure()
-      #   run: |
-      #     sudo apt-get update
-      #     sudo apt-get install -y libxml2-utils
-      #     /usr/bin/xmllint --version
-      #     yarn xunit-to-junit smoke-tests-electron
+      - name: Convert XUnit to JUnit
+        id: xunit-to-junit
+        if: success() || failure()
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y libxml2-utils
+          /usr/bin/xmllint --version
+          yarn xunit-to-junit smoke-tests-electron
 
       # - name: Set TestRail Run Title
       #   id: set-testrail-run-title
@@ -147,25 +136,64 @@ jobs:
       #   if: always()
       #   run: trcli --host "https://posit.testrail.io/" --project Positron --username testrailautomation@posit.co --key ${{ secrets.TESTRAIL_API_KEY}} parse_junit --file ".build/logs/smoke-tests-electron/test-results/results.xml" --case-matcher name --title "$TESTRAIL_TITLE" --close-run
 
-    #   - name: Upload run artifacts
-    #     if: always()
-    #     uses: actions/upload-artifact@v4
-    #     with:
-    #       name: run-artifacts
-    #       path: .build/logs/smoke-tests-electron/
-    # outputs:
-    #   target: ${{ env.SMOKETEST_TARGET }}
-
-  slack-notification:
-    name: "Send Slack notification"
-    runs-on: ubuntu-latest
-    needs: linux
-    if: ${{ failure() && needs.linux.outputs.target  == 'smoketest-all' }}
-    steps:
-      - name: "Send Slack notification"
-        uses: testlabauto/action-test-results-to-slack@v0.0.6
+      - name: Upload run artifacts
+        if: always()
+        uses: actions/upload-artifact@v4
         with:
-          github_token: ${{ secrets.POSITRON_GITHUB_PAT }}
-          slack_token: ${{ secrets.SMOKE_TESTS_SLACK_TOKEN }}
-          slack_channel: C07FR1JNZNJ #positron-test-results channel
-          suite_name: Positron Merge to Main Test Suite
+          name: run-artifacts
+          path: .build/logs/smoke-tests-electron/
+    outputs:
+      target: ${{ env.SMOKETEST_TARGET }}
+
+  unit-integration-tests:
+    runs-on: ubuntu-latest
+    timeout-minutes: 20
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      POSITRON_BUILD_NUMBER: 0 # CI skips building releases
+      _R_CHECK_FUTURE_FILE_TIMESTAMPS_: false # this check can be flaky in the R pkg tests
+      _R_CHECK_CRAN_INCOMING_: false
+      _R_CHECK_SYSTEM_CLOCK_: false
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: actions/setup-node@v4
+        with:
+          node-version-file: .nvmrc
+
+      - name: Cache node_modules, build, extensions, and remote
+        uses: ./.github/actions/cache-multi-paths
+
+      - name: Setup Build and Compile
+        uses: ./.github/actions/setup-build-env
+
+      - name: Install Positron License
+        uses: ./.github/actions/install-license
+        with:
+          github-token: ${{ secrets.POSITRON_GITHUB_PAT }}
+          license-key: ${{ secrets.POSITRON_DEV_LICENSE }}
+
+      - name: Compile Integration Tests
+        run: yarn --cwd test/integration/browser compile
+
+      - name: Run Unit Tests (node.js)
+        id: nodejs-unit-tests
+        run: yarn test-node
+
+      - name: Run Integration Tests (Electron)
+        id: electron-integration-tests
+        run: DISPLAY=:10 ./scripts/test-integration-pr.sh
+
+  # slack-notification:
+  #   name: "Send Slack notification"
+  #   runs-on: ubuntu-latest
+  #   needs: unit-integration-tests
+  #   if: ${{ failure() && needs.linux.outputs.target  == 'smoketest-all' }}
+  #   steps:
+  #     - name: "Send Slack notification"
+  #       uses: testlabauto/action-test-results-to-slack@v0.0.6
+  #       with:
+  #         github_token: ${{ secrets.POSITRON_GITHUB_PAT }}
+  #         slack_token: ${{ secrets.SMOKE_TESTS_SLACK_TOKEN }}
+  #         slack_channel: C07FR1JNZNJ #positron-test-results channel
+  #         suite_name: Positron Merge to Main Test Suite
