simulate failure

diff --git a/.github/workflows/positron-python-nightly.yml b/.github/workflows/positron-python-nightly.yml
--- a/.github/workflows/positron-python-nightly.yml
+++ b/.github/workflows/positron-python-nightly.yml
@@ -68,8 +68,15 @@ jobs:
       - name: Install test requirements
         run: python -m pip install -r build/test-requirements.txt
 
+      # - name: Run Python unit tests
+      #   run: python python_files/tests/run_all.py --junit-xml=python-unit-test-results.xml
       - name: Run Python unit tests
-        run: python python_files/tests/run_all.py --junit-xml=python-unit-test-results.xml
+        run: |
+          if [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.python }}" == "3.11" ]]; then
+            echo "Simulated failure for testing notifications" && exit 1
+          else
+            python python_files/tests/run_all.py --junit-xml=python-unit-test-results.xml
+          fi
 
       - name: Upload test artifacts
         uses: actions/upload-artifact@v4
