disable browser

diff --git a/.github/workflows/positron-full-test.yml b/.github/workflows/positron-full-test.yml
--- a/.github/workflows/positron-full-test.yml
+++ b/.github/workflows/positron-full-test.yml
@@ -172,83 +172,83 @@ jobs:
           path: playwright-report/
           retention-days: 7
 
-  e2e-browser-tests:
-    runs-on: ubuntu-latest-4x
-    timeout-minutes: 40
-    env:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      POSITRON_BUILD_NUMBER: 0 # CI skips building releases
-      _R_CHECK_FUTURE_FILE_TIMESTAMPS_: false # this check can be flaky in the R pkg tests
-      _R_CHECK_CRAN_INCOMING_: false
-      _R_CHECK_SYSTEM_CLOCK_: false
-    steps:
-      - uses: actions/checkout@v4
+  # e2e-browser-tests:
+  #   runs-on: ubuntu-latest-4x
+  #   timeout-minutes: 40
+  #   env:
+  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     POSITRON_BUILD_NUMBER: 0 # CI skips building releases
+  #     _R_CHECK_FUTURE_FILE_TIMESTAMPS_: false # this check can be flaky in the R pkg tests
+  #     _R_CHECK_CRAN_INCOMING_: false
+  #     _R_CHECK_SYSTEM_CLOCK_: false
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: .nvmrc
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: .nvmrc
 
-      - name: Cache node_modules, build, extensions, and remote
-        uses: ./.github/actions/cache-multi-paths
+  #     - name: Cache node_modules, build, extensions, and remote
+  #       uses: ./.github/actions/cache-multi-paths
 
-      - name: Setup Build and Compile
-        uses: ./.github/actions/setup-build-env
+  #     - name: Setup Build and Compile
+  #       uses: ./.github/actions/setup-build-env
 
-      - name: Install Positron License
-        uses: ./.github/actions/install-license
-        with:
-          github-token: ${{ secrets.POSITRON_GITHUB_PAT }}
-          license-key: ${{ secrets.POSITRON_DEV_LICENSE }}
+  #     - name: Install Positron License
+  #       uses: ./.github/actions/install-license
+  #       with:
+  #         github-token: ${{ secrets.POSITRON_GITHUB_PAT }}
+  #         license-key: ${{ secrets.POSITRON_DEV_LICENSE }}
 
-      - name: Setup E2E Test Environment
-        uses: ./.github/actions/setup-test-env
-        with:
-          aws-role-to-assume: ${{ secrets.QA_AWS_RO_ROLE }}
-          aws-region: ${{ secrets.QA_AWS_REGION }}
-          github-token: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Setup E2E Test Environment
+  #       uses: ./.github/actions/setup-test-env
+  #       with:
+  #         aws-role-to-assume: ${{ secrets.QA_AWS_RO_ROLE }}
+  #         aws-region: ${{ secrets.QA_AWS_REGION }}
+  #         github-token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Run Tests (Web)
-        env:
-          POSITRON_PY_VER_SEL: 3.10.12
-          POSITRON_R_VER_SEL: 4.4.0
-        id: electron-web-smoke-tests
-        # run: DISPLAY=:10 yarn smoketest-web --tracing
-        run: DISPLAY=:10 npx playwright test --project e2e-browser --workers 1
+  #     - name: Run Tests (Web)
+  #       env:
+  #         POSITRON_PY_VER_SEL: 3.10.12
+  #         POSITRON_R_VER_SEL: 4.4.0
+  #       id: electron-web-smoke-tests
+  #       # run: DISPLAY=:10 yarn smoketest-web --tracing
+  #       run: DISPLAY=:10 npx playwright test --project e2e-browser --workers 1
 
-      # - name: Convert XUnit to JUnit
-      #   id: xunit-to-junit
-      #   if: success() || failure()
-      #   run: |
-      #     sudo apt-get update
-      #     sudo apt-get install -y libxml2-utils
-      #     yarn xunit-to-junit smoke-tests-browser
+  #     # - name: Convert XUnit to JUnit
+  #     #   id: xunit-to-junit
+  #     #   if: success() || failure()
+  #     #   run: |
+  #     #     sudo apt-get update
+  #     #     sudo apt-get install -y libxml2-utils
+  #     #     yarn xunit-to-junit smoke-tests-browser
 
-      # - name: Publish Web Test Report
-      #   uses: mikepenz/action-junit-report@v4
-      #   if: success() || failure()
-      #   with:
-      #     report_paths: "**/.build/logs/smoke-tests-browser/test-results/xunit-results.xml"
-      #     check_name: "Web Test Results"
-      #     token: ${{ secrets.GITHUB_TOKEN }}
+  #     # - name: Publish Web Test Report
+  #     #   uses: mikepenz/action-junit-report@v4
+  #     #   if: success() || failure()
+  #     #   with:
+  #     #     report_paths: "**/.build/logs/smoke-tests-browser/test-results/xunit-results.xml"
+  #     #     check_name: "Web Test Results"
+  #     #     token: ${{ secrets.GITHUB_TOKEN }}
 
-      # - name: Upload Artifacts - Browser
-      #   if: always()
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: run-artifacts-browser
-      #     path: .build/logs/smoke-tests-browser/
+  #     # - name: Upload Artifacts - Browser
+  #     #   if: always()
+  #     #   uses: actions/upload-artifact@v4
+  #     #   with:
+  #     #     name: run-artifacts-browser
+  #     #     path: .build/logs/smoke-tests-browser/
 
-      - name: Upload Playwright Report
-        uses: actions/upload-artifact@v4
-        if: ${{ !cancelled() }}
-        with:
-          name: playwright-report
-          path: playwright-report/
-          retention-days: 7
+  #     - name: Upload Playwright Report
+  #       uses: actions/upload-artifact@v4
+  #       if: ${{ !cancelled() }}
+  #       with:
+  #         name: playwright-report
+  #         path: playwright-report/
+  #         retention-days: 7
 
-      - name: Clean up license files
-        if: always()
-        run: cd .. && rm -rf positron-license
+  #     - name: Clean up license files
+  #       if: always()
+  #       run: cd .. && rm -rf positron-license
 
   # slack-notification:
   #   name: "slack-notification"
