disable web

diff --git a/.github/workflows/positron-full-test.yml b/.github/workflows/positron-full-test.yml
--- a/.github/workflows/positron-full-test.yml
+++ b/.github/workflows/positron-full-test.yml
@@ -75,14 +75,14 @@ jobs:
             ../positron-license/pdol/target/debug/pdol_rsa
 
       # ---- START: move to shared SETUP ----
-      # - name: Checkout test licensing tool
-      #   run: |
-      #     cd ..
-      #     mkdir positron-license
-      #     cd positron-license
-      #     git clone https://${{ secrets.POSITRON_GITHUB_PAT }}@github.com/posit-dev/positron-license.git .
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.POSITRON_GITHUB_PAT }}
+      - name: Checkout test licensing tool
+        run: |
+          cd ..
+          mkdir positron-license
+          cd positron-license
+          git clone https://${{ secrets.POSITRON_GITHUB_PAT }}@github.com/posit-dev/positron-license.git .
+        env:
+          GITHUB_TOKEN: ${{ secrets.POSITRON_GITHUB_PAT }}
 
       - name: Install Rust latest nightly
         uses: actions-rs/toolchain@v1
@@ -90,18 +90,18 @@ jobs:
           toolchain: nightly
           override: true
 
-      # - name: Build licensing tool
-      #   run: |
-      #     cd ..
-      #     cd positron-license/pdol
-      #     cargo build
+      - name: Build licensing tool
+        run: |
+          cd ..
+          cd positron-license/pdol
+          cargo build
 
-      # - name: Echo license
-      #   run: |
-      #     cd ..
-      #     cd positron-license/pdol/target/debug
-      #     echo "${{ secrets.POSITRON_DEV_LICENSE }}" > pdol_rsa
-      #     chmod 600 pdol_rsa
+      - name: Echo license
+        run: |
+          cd ..
+          cd positron-license/pdol/target/debug
+          echo "${{ secrets.POSITRON_DEV_LICENSE }}" > pdol_rsa
+          chmod 600 pdol_rsa
 
       - name: Setup Build Environment
         run: |
@@ -529,20 +529,20 @@ jobs:
           python -m pip install -r requirements.txt
           python -m pip install ipykernel trcli
 
-      - name: Run Web Smoke Tests
-        env:
-          POSITRON_PY_VER_SEL: 3.10.12
-          POSITRON_R_VER_SEL: 4.4.0
-        id: electron-web-smoke-tests
-        run: DISPLAY=:10 yarn smoketest-web --tracing
+      # - name: Run Web Smoke Tests
+      #   env:
+      #     POSITRON_PY_VER_SEL: 3.10.12
+      #     POSITRON_R_VER_SEL: 4.4.0
+      #   id: electron-web-smoke-tests
+      #   run: DISPLAY=:10 yarn smoketest-web --tracing
 
-      - name: Convert XUnit to JUnit
-        id: xunit-to-junit
-        if: success() || failure()
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y libxml2-utils
-          yarn xunit-to-junit smoke-tests-browser
+      # - name: Convert XUnit to JUnit
+      #   id: xunit-to-junit
+      #   if: success() || failure()
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y libxml2-utils
+      #     yarn xunit-to-junit smoke-tests-browser
 
       - name: Clean up license files
         if: always()
@@ -550,13 +550,13 @@ jobs:
           cd ..
           rm -rf positron-license
 
-      - name: Publish Web Test Report
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure()
-        with:
-          report_paths: "**/.build/logs/smoke-tests-browser/test-results/xunit-results.xml"
-          check_name: "Web Test Results"
-          token: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Publish Web Test Report
+      #   uses: mikepenz/action-junit-report@v4
+      #   if: success() || failure()
+      #   with:
+      #     report_paths: "**/.build/logs/smoke-tests-browser/test-results/xunit-results.xml"
+      #     check_name: "Web Test Results"
+      #     token: ${{ secrets.GITHUB_TOKEN }}
 
       # - name: Set TestRail Run Title
       #   id: set-testrail-run-title
