full and pr

diff --git a/.github/workflows/positron-full-test.yml b/.github/workflows/positron-full-test.yml
--- a/.github/workflows/positron-full-test.yml
+++ b/.github/workflows/positron-full-test.yml
@@ -2,96 +2,99 @@ name: "Positron: Full Test Suite"
 
 # Run tests daily at 4am UTC (11p EST) on weekdays for now, or manually
 on:
-  schedule:
-    - cron: "0 4 * * 1-5"
-  workflow_dispatch:
+  # schedule:
+  #   - cron: "0 4 * * 1-5"
+  # workflow_dispatch:
+  pull_request:
+    branches:
+      - main
 
 permissions:
   id-token: write
   contents: read
 
 jobs:
-  unit-tests:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    env:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      POSITRON_BUILD_NUMBER: 0 # CI skips building releases
-    steps:
-      - uses: actions/checkout@v4
+  # unit-tests:
+  #   runs-on: ubuntu-latest
+  #   timeout-minutes: 30
+  #   env:
+  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     POSITRON_BUILD_NUMBER: 0 # CI skips building releases
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: .nvmrc
+  #     - uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: .nvmrc
 
-      - name: Cache node_modules, build, extensions, and remote
-        uses: ./.github/actions/cache-multi-paths
+  #     - name: Cache node_modules, build, extensions, and remote
+  #       uses: ./.github/actions/cache-multi-paths
 
-      - name: Setup Build and Compile
-        uses: ./.github/actions/setup-build-env
+  #     - name: Setup Build and Compile
+  #       uses: ./.github/actions/setup-build-env
 
-      - name: Run Unit Tests (Electron)
-        id: electron-unit-tests
-        run: DISPLAY=:10 ./scripts/test.sh
+  #     - name: Run Unit Tests (Electron)
+  #       id: electron-unit-tests
+  #       run: DISPLAY=:10 ./scripts/test.sh
 
-      - name: Run Unit Tests (node.js)
-        id: nodejs-unit-tests
-        run: yarn test-node
+  #     - name: Run Unit Tests (node.js)
+  #       id: nodejs-unit-tests
+  #       run: yarn test-node
 
-      - name: Run Unit Tests (Browser, Chromium)
-        id: browser-unit-tests
-        run: DISPLAY=:10 yarn test-browser-no-install --browser chromium
+  #     - name: Run Unit Tests (Browser, Chromium)
+  #       id: browser-unit-tests
+  #       run: DISPLAY=:10 yarn test-browser-no-install --browser chromium
 
-  integration-tests:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    env:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      POSITRON_BUILD_NUMBER: 0 # CI skips building releases
-    steps:
-      - uses: actions/checkout@v4
+  # integration-tests:
+  # runs-on: ubuntu-latest
+  # timeout-minutes: 30
+  # env:
+  #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #   POSITRON_BUILD_NUMBER: 0 # CI skips building releases
+  # steps:
+  #   - uses: actions/checkout@v4
 
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: .nvmrc
+  #   - uses: actions/setup-node@v4
+  #     with:
+  #       node-version-file: .nvmrc
 
-      - name: Cache node_modules, build, extensions, and remote
-        uses: ./.github/actions/cache-multi-paths
+  #   - name: Cache node_modules, build, extensions, and remote
+  #     uses: ./.github/actions/cache-multi-paths
 
-      - name: Setup Build and Compile
-        uses: ./.github/actions/setup-build-env
+  #   - name: Setup Build and Compile
+  #     uses: ./.github/actions/setup-build-env
 
-      - name: Install Positron License
-        uses: ./.github/actions/install-license
-        with:
-          github-token: ${{ secrets.POSITRON_GITHUB_PAT }}
-          license-key: ${{ secrets.POSITRON_DEV_LICENSE }}
+  #   - name: Install Positron License
+  #     uses: ./.github/actions/install-license
+  #     with:
+  #       github-token: ${{ secrets.POSITRON_GITHUB_PAT }}
+  #       license-key: ${{ secrets.POSITRON_DEV_LICENSE }}
 
-      - name: Setup R
-        uses: ./.github/actions/install-r
-        with:
-          version: "4.4.0"
+  #   - name: Setup R
+  #     uses: ./.github/actions/install-r
+  #     with:
+  #       version: "4.4.0"
 
-      - name: Compile Integration Tests
-        run: yarn --cwd test/integration/browser compile
+  #   - name: Compile Integration Tests
+  #     run: yarn --cwd test/integration/browser compile
 
-      - name: Run Integration Tests (Electron)
-        id: electron-integration-tests
-        run: DISPLAY=:10 ./scripts/test-integration.sh
+  #   - name: Run Integration Tests (Electron)
+  #     id: electron-integration-tests
+  #     run: DISPLAY=:10 ./scripts/test-integration.sh
 
-      - name: Run Integration Tests (Remote)
-        if: ${{ job.status != 'cancelled' && (success() || failure()) }}
-        id: electron-remote-integration-tests
-        run: DISPLAY=:10 ./scripts/test-remote-integration.sh
+  #   - name: Run Integration Tests (Remote)
+  #     if: ${{ job.status != 'cancelled' && (success() || failure()) }}
+  #     id: electron-remote-integration-tests
+  #     run: DISPLAY=:10 ./scripts/test-remote-integration.sh
 
-      - name: Run Integration Tests (Browser, Chromium)
-        if: ${{ job.status != 'cancelled' && (success() || failure()) }}
-        id: browser-integration-tests
-        run: DISPLAY=:10 ./scripts/test-web-integration.sh --browser chromium
+  #   - name: Run Integration Tests (Browser, Chromium)
+  #     if: ${{ job.status != 'cancelled' && (success() || failure()) }}
+  #     id: browser-integration-tests
+  #     run: DISPLAY=:10 ./scripts/test-web-integration.sh --browser chromium
 
-      - name: Clean up license files
-        if: always()
-        run: cd .. && rm -rf positron-license
+  #   - name: Clean up license files
+  #     if: always()
+  #     run: cd .. && rm -rf positron-license
 
   e2e-electron-tests:
     runs-on: ubuntu-latest-8x
@@ -127,40 +130,42 @@ jobs:
           POSITRON_PY_VER_SEL: 3.10.12
           POSITRON_R_VER_SEL: 4.4.0
         id: electron-smoke-tests
-        run: DISPLAY=:10 yarn smoketest-all --tracing --skip-cleanup
+        # run: DISPLAY=:10 yarn smoketest-all --tracing --skip-cleanup
+        run: DISPLAY=:10 npx playwright test --project e2e-electron --workers 1
 
-      - name: Convert XUnit to JUnit
-        id: xunit-to-junit
-        if: success() || failure()
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y libxml2-utils
-          yarn xunit-to-junit smoke-tests-electron
+      # - name: Convert XUnit to JUnit
+      #   id: xunit-to-junit
+      #   if: success() || failure()
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y libxml2-utils
+      #     yarn xunit-to-junit smoke-tests-electron
 
-      - name: Publish Electron Test Report
-        uses: mikepenz/action-junit-report@v4
-        if: success() || failure()
-        with:
-          report_paths: "**/.build/logs/smoke-tests-electron/test-results/xunit-results.xml"
-          check_name: "Electron Test Results"
-          token: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Publish Electron Test Report
+      #   uses: mikepenz/action-junit-report@v4
+      #   if: success() || failure()
+      #   with:
+      #     report_paths: "**/.build/logs/smoke-tests-electron/test-results/junit.xml"
+      #     check_name: "Electron Test Results"
+      #     token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Set TestRail Run Title
         id: set-testrail-run-title
-        if: steps.xunit-to-junit == 'success'
+        if: ${{ !cancelled() }}
         run: echo "TESTRAIL_TITLE=$(date +'%Y-%m-%d') Nightly Smoke Tests - $GITHUB_REF_NAME" >> $GITHUB_ENV
 
       - name: Upload Test Results to TestRail (Electron ONLY)
         id: testrail-upload
-        if: steps.xunit-to-junit == 'success'
+        if: ${{ !cancelled() }}
         run: trcli --host "https://posit.testrail.io/" --project Positron --username testrailautomation@posit.co --key ${{ secrets.TESTRAIL_API_KEY}} parse_junit --file ".build/logs/smoke-tests-electron/test-results/xunit-results.xml" --case-matcher name --title "$TESTRAIL_TITLE" --close-run
 
-      - name: Upload Artifacts - Electron
-        if: always()
+      - name: Upload Playwright Report
         uses: actions/upload-artifact@v4
+        if: ${{ !cancelled() }}
         with:
-          name: run-artifacts-electron
-          path: .build/logs/smoke-tests-electron/
+          name: playwright-report
+          path: playwright-report/
+          retention-days: 7
 
   e2e-browser-tests:
     runs-on: ubuntu-latest-4x
@@ -234,10 +239,9 @@ jobs:
   slack-notification:
     name: "slack-notification"
     runs-on: ubuntu-latest
-    needs:
-      [
-        "unit-tests",
-        "integration-tests",
+    needs: [
+        # "unit-tests",
+        # "integration-tests",
         "e2e-electron-tests",
         "e2e-browser-tests",
       ]
