wflow

diff --git a/.github/workflows/positron-merge-to-main.yml b/.github/workflows/positron-merge-to-main.yml
--- a/.github/workflows/positron-merge-to-main.yml
+++ b/.github/workflows/positron-merge-to-main.yml
@@ -145,9 +145,10 @@ jobs:
     outputs:
       target: ${{ env.SMOKETEST_TARGET }}
 
-  unit-integration:
-    runs-on: ubuntu-latest
-    timeout-minutes: 20
+  linux:
+    name: Tests on Linux
+    runs-on: ubuntu-latest-8x
+    timeout-minutes: 45
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       POSITRON_BUILD_NUMBER: 0 # CI skips building releases
@@ -173,6 +174,13 @@ jobs:
           github-token: ${{ secrets.POSITRON_GITHUB_PAT }}
           license-key: ${{ secrets.POSITRON_DEV_LICENSE }}
 
+      - name: Setup E2E Test Environment
+        uses: ./.github/actions/setup-test-env
+        with:
+          aws-role-to-assume: ${{ secrets.QA_AWS_RO_ROLE }}
+          aws-region: ${{ secrets.QA_AWS_REGION }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Compile Integration Tests
         run: yarn --cwd test/integration/browser compile
 
@@ -184,16 +192,52 @@ jobs:
         id: electron-integration-tests
         run: DISPLAY=:10 ./scripts/test-integration-pr.sh
 
-  # slack-notification:
-  #   name: "Send Slack notification"
-  #   runs-on: ubuntu-latest
-  #   needs: unit-integration-tests
-  #   if: ${{ failure() && needs.linux.outputs.target  == 'smoketest-all' }}
-  #   steps:
-  #     - name: "Send Slack notification"
-  #       uses: testlabauto/action-test-results-to-slack@v0.0.6
-  #       with:
-  #         github_token: ${{ secrets.POSITRON_GITHUB_PAT }}
-  #         slack_token: ${{ secrets.SMOKE_TESTS_SLACK_TOKEN }}
-  #         slack_channel: C07FR1JNZNJ #positron-test-results channel
-  #         suite_name: Positron Merge to Main Test Suite
+      - name: Run Smoke Tests (Electron)
+        if: success() || failure()
+        env:
+          POSITRON_PY_VER_SEL: 3.10.12
+          POSITRON_R_VER_SEL: 4.4.0
+        id: electron-smoke-tests
+        run: DISPLAY=:10 yarn ${{ env.SMOKETEST_TARGET }} --tracing --parallel --jobs 2 --skip-cleanup
+
+      # - name: Convert XUnit to JUnit
+      #   id: xunit-to-junit
+      #   if: success() || failure()
+      #   run: |
+      #     sudo apt-get update
+      #     sudo apt-get install -y libxml2-utils
+      #     /usr/bin/xmllint --version
+      #     yarn xunit-to-junit smoke-tests-electron
+
+      # - name: Set TestRail Run Title
+      #   id: set-testrail-run-title
+      #   if: always()
+      #   run: echo "TESTRAIL_TITLE=$(date +'%Y-%m-%d') Smoke Tests on branch $GITHUB_REF_NAME" >> $GITHUB_ENV
+
+      # - name: Upload Test Results to TestRail
+      #   id: testrail-upload
+      #   if: always()
+      #   run: trcli --host "https://posit.testrail.io/" --project Positron --username testrailautomation@posit.co --key ${{ secrets.TESTRAIL_API_KEY}} parse_junit --file ".build/logs/smoke-tests-electron/test-results/results.xml" --case-matcher name --title "$TESTRAIL_TITLE" --close-run
+
+      # - name: Upload run artifacts
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: run-artifacts
+      #     path: .build/logs/smoke-tests-electron/
+    outputs:
+      target: ${{ env.SMOKETEST_TARGET }}
+
+  slack-notification:
+    name: "Send Slack notification"
+    runs-on: ubuntu-latest
+    needs: linux
+    if: ${{ failure() && needs.linux.outputs.target  == 'smoketest-all' }}
+    steps:
+      - name: "Send Slack notification"
+        uses: testlabauto/action-test-results-to-slack@v0.0.6
+        with:
+          github_token: ${{ secrets.POSITRON_GITHUB_PAT }}
+          slack_token: ${{ secrets.SMOKE_TESTS_SLACK_TOKEN }}
+          slack_channel: C07FR1JNZNJ #positron-test-results channel
+          suite_name: Positron Merge to Main Test Suite
