enable TR again

diff --git a/.github/workflows/positron-full-test.yml b/.github/workflows/positron-full-test.yml
--- a/.github/workflows/positron-full-test.yml
+++ b/.github/workflows/positron-full-test.yml
@@ -138,15 +138,15 @@ jobs:
         # run: DISPLAY=:10 yarn smoketest-all --tracing --skip-cleanup
         run: DISPLAY=:10 npx playwright test --project e2e-electron --workers 1 --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
 
-      # - name: Set TestRail Run Title
-      #   id: set-testrail-run-title
-      #   if: ${{ !cancelled() }}
-      #   run: echo "TESTRAIL_TITLE=$(date +'%Y-%m-%d') Nightly Smoke Tests - $GITHUB_REF_NAME" >> $GITHUB_ENV
+      - name: Set TestRail Run Title
+        id: set-testrail-run-title
+        if: ${{ !cancelled() }}
+        run: echo "TESTRAIL_TITLE=$(date +'%Y-%m-%d') Nightly Smoke Tests - $GITHUB_REF_NAME" >> $GITHUB_ENV
 
-      # - name: Upload Test Results to TestRail (Electron ONLY)
-      #   id: testrail-upload
-      #   if: ${{ !cancelled() }}
-      #   run: trcli --host "https://posit.testrail.io/" --project Positron --username testrailautomation@posit.co --key ${{ secrets.TESTRAIL_API_KEY}} parse_junit --file ".build/logs/smoke-tests-electron/test-results/xunit-results.xml" --case-matcher name --title "$TESTRAIL_TITLE" --close-run
+      - name: Upload Test Results to TestRail (Electron ONLY)
+        id: testrail-upload
+        if: ${{ !cancelled() }}
+        run: trcli --host "https://posit.testrail.io/" --project Positron --username testrailautomation@posit.co --key ${{ secrets.TESTRAIL_API_KEY}} parse_junit --file "./test-results/junit.xml" --case-matcher name --title "$TESTRAIL_TITLE" --close-run
 
       - name: Upload blob report
         if: ${{ !cancelled() }}
@@ -156,10 +156,15 @@ jobs:
           path: blob-report
           retention-days: 1
 
-  e2e-report:
-    runs-on: ubuntu-latest
-    needs: ["e2e-electron-tests"]
-    if: always()
+  e2e-browser-tests:
+    runs-on: ubuntu-latest-4x
+    timeout-minutes: 40
+    env:
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      POSITRON_BUILD_NUMBER: 0 # CI skips building releases
+      _R_CHECK_FUTURE_FILE_TIMESTAMPS_: false # this check can be flaky in the R pkg tests
+      _R_CHECK_CRAN_INCOMING_: false
+      _R_CHECK_SYSTEM_CLOCK_: false
     steps:
       - uses: actions/checkout@v4
 
@@ -167,107 +172,80 @@ jobs:
         with:
           node-version-file: .nvmrc
 
-      - name: Install Playwright
-        run: npx playwright install --with-deps
+      - name: Cache node_modules, build, extensions, and remote
+        uses: ./.github/actions/cache-multi-paths
 
-      # - name: Download blob reports from GitHub Actions Artifacts
-      #   uses: actions/download-artifact@v4
+      - name: Setup Build and Compile
+        uses: ./.github/actions/setup-build-env
+
+      - name: Install Positron License
+        uses: ./.github/actions/install-license
+        with:
+          github-token: ${{ secrets.POSITRON_GITHUB_PAT }}
+          license-key: ${{ secrets.POSITRON_DEV_LICENSE }}
+
+      - name: Setup E2E Test Environment
+        uses: ./.github/actions/setup-test-env
+        with:
+          aws-role-to-assume: ${{ secrets.QA_AWS_RO_ROLE }}
+          aws-region: ${{ secrets.QA_AWS_REGION }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Run Tests (Web)
+        env:
+          POSITRON_PY_VER_SEL: 3.10.12
+          POSITRON_R_VER_SEL: 4.4.0
+        id: electron-web-smoke-tests
+        run: DISPLAY=:10 npx playwright test --project e2e-browser --workers 1
+      # - name: Publish Web Test Report
+      #   uses: mikepenz/action-junit-report@v4
+      #   if: success() || failure()
       #   with:
-      #     path: all-blob-reports
-      #     pattern: blob-report-*
-      #     merge-multiple: true
-      - name: Download blob reports from GitHub Actions Artifacts
-        uses: actions/download-artifact@v3
+      #     report_paths: "**/.build/logs/smoke-tests-browser/test-results/xunit-results.xml"
+      #     check_name: "Web Test Results"
+      #     token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Upload blob report
+        if: ${{ !cancelled() }}
+        uses: actions/upload-artifact@v3
         with:
           name: all-blob-reports
-          path: all-blob-reports
+          path: blob-report
+          retention-days: 1
 
-      - name: Merge into HTML Report
-        run: npx playwright merge-reports --reporter html ./all-blob-reports
+      - name: Clean up license files
+        if: always()
+        run: cd .. && rm -rf positron-license
 
-      - name: Upload HTML report
-        uses: actions/upload-artifact@v4
-        with:
-          name: html-report--attempt-${{ github.run_attempt }}
-          path: playwright-report
-          retention-days: 14
-  # e2e-browser-tests:
-  #   runs-on: ubuntu-latest-4x
-  #   timeout-minutes: 40
-  #   env:
-  #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #     POSITRON_BUILD_NUMBER: 0 # CI skips building releases
-  #     _R_CHECK_FUTURE_FILE_TIMESTAMPS_: false # this check can be flaky in the R pkg tests
-  #     _R_CHECK_CRAN_INCOMING_: false
-  #     _R_CHECK_SYSTEM_CLOCK_: false
-  #   steps:
-  #     - uses: actions/checkout@v4
+        e2e-report:
+          runs-on: ubuntu-latest
+          needs: ["e2e-electron-tests"]
+          if: always()
+          steps:
+            - uses: actions/checkout@v4
 
-  #     - uses: actions/setup-node@v4
-  #       with:
-  #         node-version-file: .nvmrc
+            - uses: actions/setup-node@v4
+              with:
+                node-version-file: .nvmrc
 
-  #     - name: Cache node_modules, build, extensions, and remote
-  #       uses: ./.github/actions/cache-multi-paths
+            - name: Install Playwright
+              run: npx playwright install --with-deps
 
-  #     - name: Setup Build and Compile
-  #       uses: ./.github/actions/setup-build-env
+            - name: Download blob reports from GitHub Actions Artifacts
+              uses: actions/download-artifact@v3
+              with:
+                name: all-blob-reports
+                path: all-blob-reports
 
-  #     - name: Install Positron License
-  #       uses: ./.github/actions/install-license
-  #       with:
-  #         github-token: ${{ secrets.POSITRON_GITHUB_PAT }}
-  #         license-key: ${{ secrets.POSITRON_DEV_LICENSE }}
+            - name: Merge into HTML Report
+              run: npx playwright merge-reports --reporter html ./all-blob-reports
 
-  #     - name: Setup E2E Test Environment
-  #       uses: ./.github/actions/setup-test-env
-  #       with:
-  #         aws-role-to-assume: ${{ secrets.QA_AWS_RO_ROLE }}
-  #         aws-region: ${{ secrets.QA_AWS_REGION }}
-  #         github-token: ${{ secrets.GITHUB_TOKEN }}
-
-  #     - name: Run Tests (Web)
-  #       env:
-  #         POSITRON_PY_VER_SEL: 3.10.12
-  #         POSITRON_R_VER_SEL: 4.4.0
-  #       id: electron-web-smoke-tests
-  #       # run: DISPLAY=:10 yarn smoketest-web --tracing
-  #       run: DISPLAY=:10 npx playwright test --project e2e-browser --workers 1
-
-  #     # - name: Convert XUnit to JUnit
-  #     #   id: xunit-to-junit
-  #     #   if: success() || failure()
-  #     #   run: |
-  #     #     sudo apt-get update
-  #     #     sudo apt-get install -y libxml2-utils
-  #     #     yarn xunit-to-junit smoke-tests-browser
-
-  #     # - name: Publish Web Test Report
-  #     #   uses: mikepenz/action-junit-report@v4
-  #     #   if: success() || failure()
-  #     #   with:
-  #     #     report_paths: "**/.build/logs/smoke-tests-browser/test-results/xunit-results.xml"
-  #     #     check_name: "Web Test Results"
-  #     #     token: ${{ secrets.GITHUB_TOKEN }}
-
-  #     # - name: Upload Artifacts - Browser
-  #     #   if: always()
-  #     #   uses: actions/upload-artifact@v4
-  #     #   with:
-  #     #     name: run-artifacts-browser
-  #     #     path: .build/logs/smoke-tests-browser/
-
-  #     - name: Upload Playwright Report
-  #       uses: actions/upload-artifact@v4
-  #       if: ${{ !cancelled() }}
-  #       with:
-  #         name: playwright-report
-  #         path: playwright-report/
-  #         retention-days: 7
-
-  #     - name: Clean up license files
-  #       if: always()
-  #       run: cd .. && rm -rf positron-license
+            - name: Upload HTML report
+              uses: actions/upload-artifact@v4
+              with:
+                name: html-report--attempt-${{ github.run_attempt }}
+                path: playwright-report
+                retention-days: 14
 
   # slack-notification:
   #   name: "slack-notification"
