E2E test: await bootstrap install on windows; skip during main CI run

diff --git a/.github/workflows/test-e2e-windows.yml b/.github/workflows/test-e2e-windows.yml
--- a/.github/workflows/test-e2e-windows.yml
+++ b/.github/workflows/test-e2e-windows.yml
@@ -196,7 +196,18 @@ jobs:
           CURRENTS_TAG: ${{ inputs.currents_tags || 'electron/win'}}
           ENABLE_CURRENTS_REPORTER: ${{ inputs.report_currents }}
           CURRENTS_PROJECT_ID: ${{ vars.CURRENTS_PROJECT_ID}}
-        run: npx playwright test --project "e2e-windows" --grep "${{ env.PW_TAGS }}" --workers 2 --repeat-each ${{ inputs.repeat_each }} --max-failures 10
+        run: |
+          npx playwright test test/e2e/tests/extensions/bootstrap-extensions.test.ts --project "e2e-windows" --reporter=null || true
+          BOOTSTRAP_EXIT_CODE=$?
+
+          SKIP_BOOTSTRAP=true npx playwright test --project "e2e-windows" --grep "${{ env.PW_TAGS }}" --workers 2 --repeat-each ${{ inputs.repeat_each }} --max-failures 10
+
+          # Fail the step if the bootstrap test failed
+          if [ "$BOOTSTRAP_EXIT_CODE" -ne 0 ]; then
+            echo "Bootstrap extensions test failed. Exiting with code $BOOTSTRAP_EXIT_CODE."
+            exit "$BOOTSTRAP_EXIT_CODE"
+          fi
+
 
       - name: Upload Playwright Report to S3
         if: ${{ success() || failure() }}
