skip tests

diff --git a/.github/workflows/test-unit.yml b/.github/workflows/test-unit.yml
--- a/.github/workflows/test-unit.yml
+++ b/.github/workflows/test-unit.yml
@@ -22,56 +22,56 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: .nvmrc
+      # - uses: actions/setup-node@v4
+      #   with:
+      #     node-version-file: .nvmrc
 
-      - name: Cache node_modules, build, extensions, and remote
-        uses: ./.github/actions/cache-multi-paths
+      # - name: Cache node_modules, build, extensions, and remote
+      #   uses: ./.github/actions/cache-multi-paths
 
-      - name: Attempt 1 - Setup Build and Compile
-        id: attempt1
-        uses: ./.github/actions/setup-build-env
-        continue-on-error: true
+      # - name: Attempt 1 - Setup Build and Compile
+      #   id: attempt1
+      #   uses: ./.github/actions/setup-build-env
+      #   continue-on-error: true
 
-      - name: Attempt 2 - Setup Build and Compile
-        if: ${{ steps.attempt1.outcome == 'failure' }}
-        id: attempt2
-        uses: ./.github/actions/setup-build-env
-        continue-on-error: true
+      # - name: Attempt 2 - Setup Build and Compile
+      #   if: ${{ steps.attempt1.outcome == 'failure' }}
+      #   id: attempt2
+      #   uses: ./.github/actions/setup-build-env
+      #   continue-on-error: true
 
-      - name: Attempt 3 - Setup Build and Compile
-        if: ${{ steps.attempt2.outcome == 'failure' }}
-        uses: ./.github/actions/setup-build-env
+      # - name: Attempt 3 - Setup Build and Compile
+      #   if: ${{ steps.attempt2.outcome == 'failure' }}
+      #   uses: ./.github/actions/setup-build-env
 
-      - name: Fail if Retries Exhausted
-        if: ${{ steps.attempt3.outcome == 'failure' }}
-        run: exit 1
+      # - name: Fail if Retries Exhausted
+      #   if: ${{ steps.attempt3.outcome == 'failure' }}
+      #   run: exit 1
 
-      - name: Install Positron License
-        uses: ./.github/actions/install-license
-        with:
-          github-token: ${{ secrets.POSITRON_GITHUB_PAT }}
-          license-key: ${{ secrets.POSITRON_DEV_LICENSE }}
+      # - name: Install Positron License
+      #   uses: ./.github/actions/install-license
+      #   with:
+      #     github-token: ${{ secrets.POSITRON_GITHUB_PAT }}
+      #     license-key: ${{ secrets.POSITRON_DEV_LICENSE }}
 
-      # one unit test needs this: Can list tables and fields from R connections
-      - name: Setup R
-        uses: ./.github/actions/install-r
-        with:
-          version: "4.4.0"
+      # # one unit test needs this: Can list tables and fields from R connections
+      # - name: Setup R
+      #   uses: ./.github/actions/install-r
+      #   with:
+      #     version: "4.4.0"
 
-      - name: Run Unit Tests (Electron)
-        id: electron-unit-tests
-        run: DISPLAY=:10 ./scripts/test.sh
+      # - name: Run Unit Tests (Electron)
+      #   id: electron-unit-tests
+      #   run: DISPLAY=:10 ./scripts/test.sh
 
-      - name: Run Unit Tests (node.js)
-        id: nodejs-unit-tests
-        run: npm run test-node
+      # - name: Run Unit Tests (node.js)
+      #   id: nodejs-unit-tests
+      #   run: npm run test-node
 
-      - name: Install Unit Test Dependencies
-        uses: ./.github/actions/setup-unit-test-env
+      # - name: Install Unit Test Dependencies
+      #   uses: ./.github/actions/setup-unit-test-env
 
-      - name: Run Unit Tests (Browser, Chromium)
-        id: browser-unit-tests
-        run: DISPLAY=:10 npm run test-browser-no-install --browser chromium
+      # - name: Run Unit Tests (Browser, Chromium)
+      #   id: browser-unit-tests
+      #   run: DISPLAY=:10 npm run test-browser-no-install --browser chromium
 
