Fix `OpenEditor` event on Windows (and test it) (#8816)
Addresses https://github.com/posit-dev/positron/issues/8374
Addresses https://github.com/posit-dev/positron/issues/8504
Addresses https://github.com/posit-dev/positron/issues/4651

Companion PR: https://github.com/posit-dev/ark/pull/890

Adds an optional `kind?: 'file' | 'uri'` field to the `OpenEditor`
event. This allows Ark to optionally navigate to `ark:` URIs without any
ambiguity.

Alternatively we could use something like this that isn't so easily
tripped up by Windows drive letters:
https://github.com/microsoft/vscode/blob/8623fc693bdd26bdd9c5be189f4854420aedd678/src/vs/workbench/contrib/debug/common/debugUtils.ts#L177.
I preferred to be explicit here.

In addition:

- Added extension-level tests for `navigateToFile` and `View(func)`
(real files and virtual namespaces)
- Added extension-level tests for `debug()` into virtual documents
(fallback and namespace)
- Added a bunch of test helpers to manage resources, R sessions, and
synchronise assertions
- Adjusted CI to run the tests on Windows
- Fixed a Windows issue preventing our code runner from propagating
failures
- Added top-level launch config to debug extension tests

The new test infrastructure cleans up R sessions in the teardown step.
This required adding `deleteSession()` in `positron.d.ts`. This new
method takes a session ID and so is in principle able to delete
backgroundsessions. An alternative would be to add a user-facing command
to delete the currently active session, which would work well here too.

### Release Notes

<!--
Optionally, replace `N/A` with text to be included in the next release
notes.
The `N/A` bullets are ignored. If you refer to one or more Positron
issues,
these issues are used to collect information about the feature or
bugfix, such
as the relevant language pack as determined by Github labels of type
`lang: `.
  The note will automatically be tagged with the language.

These notes are typically filled by the Positron team. If you are an
external
  contributor, you may ignore this section.
-->

#### New Features

- N/A

#### Bug Fixes

- Fixed an issue preventing the R backend from opening files on Windows
(https://github.com/posit-dev/positron/issues/8374 and
https://github.com/posit-dev/positron/issues/8504).

- Fixed an issue preventing virtual namespaces (created by Ark when
debugging or viewing a function from a package that doesn't have source
references) on Windows
(https://github.com/posit-dev/positron/issues/4651).


### QA Notes

On Windows (as wells as other OSes but this was broken on Windows):

- You should be able to navigate to existing files using
`.ps.ui.navigateToFile(*path*)`

- You should be able to `source()` a file containing e.g. `f <-
function() {}`. Close the editor and call `View()` in the console, this
should take you to the file.

- In an R package, visit a file like `R/foo.R` and call
`usethis::use_test()`. This should take you to
`tests/testthat/test-foo.R`.

All of these cases are now tested at extension level. I've added an
extension test step in the Windows E2E job as we're currently not
running
[test-integration.yml](https://github.com/posit-dev/positron/blob/main/.github/workflows/test-integration.yml)
on Windows. The step does not prevent the E2E tests from running if it
fails, but it does cause the whole job to fail at the end.

It was tricky to get these tests behaving properly on Windows and I had
to amend `code.bat` with `Start Positron` fences. I've confirmed
failures now behave properly in
https://github.com/posit-dev/positron/actions/runs/16717605620/job/47314333524.

diff --git a/.github/workflows/test-e2e-windows.yml b/.github/workflows/test-e2e-windows.yml
--- a/.github/workflows/test-e2e-windows.yml
+++ b/.github/workflows/test-e2e-windows.yml
@@ -202,6 +202,15 @@ jobs:
       - name: Send Results to GH Summary
         uses: ./.github/actions/gen-report-dir
 
+      - name: Run Extensions Test
+        id: extensions
+        continue-on-error: true
+        shell: bash
+        run: |
+          set +e
+          npm run test-extension -- -l positron-r
+          echo "exit_code=$?" >> $GITHUB_OUTPUT
+
       - name: Run Bootstrap Extensions Test
         id: bootstrap
         shell: bash
@@ -290,3 +299,9 @@ jobs:
           path: test-logs
           if-no-files-found: ignore
 
+      - name: Fail workflow if extension tests failed
+        if: |
+          steps.extensions.outputs.exit_code != '0'
+        run: |
+          echo "Extension tests failed."
+          exit 1
